/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './core/routes/__root'
import { Route as publicRouteRouteImport } from './core/routes/(public)/route'
import { Route as authRouteRouteImport } from './core/routes/(auth)/route'
import { Route as publicIndexRouteImport } from './core/routes/(public)/index'
import { Route as authSignupRouteImport } from './core/routes/(auth)/signup'
import { Route as authSigninRouteImport } from './core/routes/(auth)/signin'
import { Route as publicPostPostIdRouteImport } from './core/routes/(public)/post.$postId'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const publicPostPostIdRoute = publicPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/': typeof publicIndexRoute
  '/post/$postId': typeof publicPostPostIdRoute
}
export interface FileRoutesByTo {
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/': typeof publicIndexRoute
  '/post/$postId': typeof publicPostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/post/$postId': typeof publicPostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/signin' | '/signup' | '/' | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/signup' | '/' | '/post/$postId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(public)'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(public)/'
    | '/(public)/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(public)/post/$postId': {
      id: '/(public)/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof publicPostPostIdRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicPostPostIdRoute: typeof publicPostPostIdRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicPostPostIdRoute: publicPostPostIdRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
